// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"redis-desktop-explorer/internal/biz"
	"redis-desktop-explorer/internal/data"
	"redis-desktop-explorer/internal/service"
)

// Injectors from wire.go:

// wireApp init application.
func wireApp() (*App, func(), error) {
	dataData, cleanup, err := data.NewData()
	if err != nil {
		return nil, nil, err
	}
	connectionRepo := data.NewConnectionRepo(dataData)
	connectionUsecase := biz.NewConnectionUsecase(connectionRepo)
	connectionService := service.NewConnectionService(connectionUsecase)
	settingRepo := data.NewSettingRepo(dataData)
	settingUsecase := biz.NewSettingUsecase(settingRepo)
	settingService := service.NewSettingService(settingUsecase)
	app := NewApp(connectionService, settingService)
	return app, func() {
		cleanup()
	}, nil
}
