// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"redis-desktop-explorer/internal/biz"
	"redis-desktop-explorer/internal/data"
	"redis-desktop-explorer/internal/service"
)

// Injectors from wire.go:

// wireApp init application.
func wireApp(conn string) (*App, func(), error) {
	storage := data.NewConnectionStorage(conn)
	dataData, cleanup, err := data.NewData(storage)
	if err != nil {
		return nil, nil, err
	}
	connectionRepo := data.NewConnectionRepo(dataData)
	connectionUsecase := biz.NewConnectionUsecase(connectionRepo)
	connectionService := service.NewConnectionService(connectionUsecase)
	app := NewApp(connectionService)
	return app, func() {
		cleanup()
	}, nil
}
