// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {biz} from '../models';

export function CreateConnection(arg1:biz.Connection):Promise<void>;

export function ListConnection():Promise<any>;
