// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConnection(arg1, arg2) {
  return window['go']['service']['ConnectionService']['CreateConnection'](arg1, arg2);
}

export function ListConnection(arg1) {
  return window['go']['service']['ConnectionService']['ListConnection'](arg1);
}
