// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {biz} from '../models';

export function CreateConnection(arg1:context.Context,arg2:biz.Connection):Promise<void>;

export function ListConnection(arg1:context.Context):Promise<any>;
