// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {biz} from '../models';

export function UpdateSetting(arg1:biz.Setting):Promise<void>;
